# Do NOT update manually; changes here will be overwritten by Copier
_commit: b9204e4
_src_path: gh:open-synergy/ssi-addons-repo-template
dependency_installation_mode: OCA
generate_requirements_txt: true
include_aeroo_report: false
include_wkhtmltopdf: true
odoo_version: 8.0
rebel_module_groups: []
repo_description: opnsynid-sprint
repo_name: opnsynid-sprint
repo_slug: opnsynid-sprint
travis_apt_packages: []
travis_apt_sources: []
